# Production Configuration

debug: false

# Server Configuration for Futuristic Interface
server:
  host: "0.0.0.0"
  port: 8001
  workers: 4
  reload: false
  log_level: "info"

# CORS Configuration (Update for production domains)
cors:
  allow_origins:
    - "https://your-domain.com"
    - "https://api.your-domain.com"
  allow_credentials: true
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["*"]

# Security Settings
security:
  jwt_secret_key: "${JWT_SECRET_KEY}"
  jwt_algorithm: "HS256"
  jwt_expire_hours: 24
  api_key_header: "X-API-Key"
  rate_limit_requests: 100
  rate_limit_period: 3600

database:
  url: "${DATABASE_URL}"
  pool_size: 20
  pool_timeout: 30
  pool_recycle: 3600
  echo: false

ncbi:
  api_key: "${NCBI_API_KEY}"
  email: "${NCBI_EMAIL}"
  rate_limit: 3
  timeout: 60
  retries: 5

nlp:
  model: "en_core_sci_sm"
  batch_size: 64
  max_tokens: 512
  enable_gpu: "${NLP_ENABLE_GPU:false}"
  cache_models: true

logging:
  level: "INFO"
  format: "json"
  file: "logs/omics_oracle.log"
  max_file_size: "100MB"
  backup_count: 10

api:
  host: "0.0.0.0"
  port: "${PORT:8000}"
  workers: "${API_WORKERS:4}"
  reload: false
  debug: false

cache:
  enabled: true
  backend: "redis"
  redis_url: "${REDIS_URL}"
  default_ttl: 3600  # 1 hour
